### ISSUE TITLE
Scroll doesnt work on Cart Side View (iOS) when multiple items are added to the cart

### ISSUE THREAD

**Issue by achadee** [vercel/commerce#344]
https://user-images.githubusercontent.com/5952918/120188328-53e00400-c259-11eb-8c30-6f79d8297098.mov

Tested on the vercel demo store as well. I'll try and figure out the css prop tomorrow

**Comment by achadee** [comment]
Here is my solution for anyone facing the same problem (warning its not too elegant)

I render a different sidebar for mobile that has a different scroll setting and layout (ignores the backdrop etc)

```jsx
<Portal>
      {open ? (
        <div>
          <div className={cn('hidden', 'md:block', s.root)} ref={ref}>
            <div className="absolute inset-0 overflow-scroll">
              <div
                className="absolute inset-0 bg-black bg-opacity-50 transition-opacity"
                onClick={onClose}
              />
              <section className="absolute inset-y-0 right-0 max-w-full flex sm:pl-16 outline-none">
                <div className="h-full md:w-screen md:max-w-md">
                  <div className="h-full flex flex-col text-base bg-accents-1 shadow-xl overflow-y-scroll">
                    {children}
                  </div>
                </div>
              </section>
            </div>
          </div>
          <div className={cn('block', 'md:hidden', s.mobileRoot)} ref={ref}>
            {children}
          </div>
        </div>
      ) : null}
    </Portal>
```

```css
.root {
  @apply fixed inset-0 h-full;
  z-index: 10000;
}


.mobileRoot {
  @apply fixed top-0 bottom-0 left-0 right-0 bg-white h-screen;
  z-index: 10000;

  overflow: auto;
  -webkit-overflow-scrolling: touch;
  transform: translate3d(0,0,0);

}
```
