### ISSUE TITLE
Add dockerfile for hosting outside of vercel

### ISSUE THREAD

**Issue by flyboarder** [vercel/commerce#481]

**Comment by okbel** [comment]
We're not planning on building a docker image.

**Comment by Aryojaam** [comment]
Here is a sample Dockerfile for running the project in docker.  Just make sure before running, make sure:
* you have your `site/.env.local` with the correct variables for your package set up. I am using the vendure package so my env file looks sth like this
```
COMMERCE_PROVIDER=@vercel/commerce-vendure

NEXT_PUBLIC_VENDURE_SHOP_API_URL=http://localhost:3000/shop-api
NEXT_PUBLIC_VENDURE_LOCAL_URL=/vendure-shop-api
```
*  secondly, your vendure backend is running and reachable

So, here is the `Dockerfile` which is located in the root of your project:
```
FROM node:latest
EXPOSE 8000

WORKDIR /app/

COPY package.json /app/
COPY turbo.json /app/
COPY yarn.lock /app/
COPY site/ /app/site/
COPY packages/ /app/packages/

RUN yarn
# remove comment for production
# RUN yarn build

WORKDIR /app/site/

# use for production instead of dev
# CMD yarn next start -p 8000
CMD yarn next dev -p 8000
```

Additionally I use `docker-compose` for starting.
Here is a sample `docker-compose.yml` which should also be located in the root folder of the project as well.
```
version: '3.1'

services:
  server:
    build: ./
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./site/:/app/site/
      - ./packages/:/app/packages/
```
with this setup, you just need to run `docker-compose up` and you should have your site running on `localhost:8000` after building is complete.
I hope this helps! :)
